# Generated by Django 2.2 on 2020-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('location', models.CharField(choices=[('bengaluru', 'Bengaluru'), ('hydrabad', 'Hydrabad'), ('gurgaon', 'Gurgaon')], default='all-india', max_length=40)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
